export const kifuNotationMap: { [key: string]: string } = {
  '▲': 'Black (Sente, the first player) indicator',
  '△': 'White (Gote, the second player) indicator',
  'P': 'Pawn',
  'L': 'Lance',
  'N': 'Knight',
  'S': 'Silver',
  'G': 'Gold',
  'B': 'Bishop',
  'R': 'Rook',
  'K': 'King',
  '+P': 'Promoted Pawn',
  '+L': 'Promoted Lance',
  '+N': 'Promoted Knight',
  '+S': 'Promoted Silver',
  '+B': 'Promoted Bishop',
  '+R': 'Promoted Rook',
  '-': 'Normal Move',
  'x': 'Capture',
  '*': 'Drop (piece being dropped from hand)',
  '+': 'Promotion (piece is promoted)',
  '=': 'No Promotion (player chose not to promote)',
  '同': 'Same Square Capture (dou): If a piece captures the opponent\'s piece on the same square where the opponent just moved, the destination coordinates can be replaced with the character \'同\', meaning \"same.\" This always involves a capture.',
  '右': 'Directional Indicator: Right',
  '左': 'Directional Indicator: Left',
  '上': 'Directional Indicator: Forward/Up',
  '引': 'Directional Indicator: Backward/Pull',
  '寄': 'Directional Indicator: Sideways',
  '直': 'Directional Indicator: Straight (when a piece could also move diagonally)',
  '打': 'Drop (Japanese notation)',
  '成': 'Promotion (Japanese notation)',
};